version: '3'
services:
  gitbook:
    image: fellah/gitbook
    container_name: gitbook-server
    ports:
      - "4000:4000"
    volumes:
      - ./:/srv/gitbook
    command: /bin/bash -c "gitbook install && gitbook serve"
    restart: always